# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: charlesdesouza88@gmail.com
author_name: Charles M Desouza
contract_name: hello_world
preset_name: starter
project_name: SoundChain

